### PR TITLE
Seq data to lane fastq@0.1.0

### PR DESCRIPTION
**Pull request by lindaxiang**

### CODE REVIEW

**Comment by junjun-zhang** [comment]
Looking good. Not sure whether it's appropriate to consider a package that does both this and https://github.com/icgc-argo-workflows/dna-seq-processing-tools/tree/main/tools/seq-data-to-lane-bam? It would make sense if the only difference is the output format, which can then be controlled by a parameter (with sensible default).

**Comment by lindaxiang** [comment]
> Looking good. Not sure whether it's appropriate to consider a package that does both this and https://github.com/icgc-argo-workflows/dna-seq-processing-tools/tree/main/tools/seq-data-to-lane-bam? It would make sense if the only difference is the output format, which can then be controlled by a parameter (with sensible default).

Thanks @junjun-zhang . Very good thoughts! We can consider the merged version as next iteration of the tool.

**Review by junjun-zhang — APPROVED** [review]

**Review by lDesiree — COMMENTED** [review]
The code looks good but I agree that we should avoid redundancy.

**Comment by lindaxiang** [comment]
> The code looks good but I agree that we should avoid redundancy.

Thanks Desiree. Totally agree with you.

**Pull request merged**
